### PR TITLE
Retry poll

### PR DESCRIPTION
**Pull request by jolaf**
Fixes two typical runtime issues.

One. When parsing returned JSON fails with exception, return analysis fails:
```python3
2021-11-15 08:32:34 urllib3.connectionpool	DEBUG	https://api.ssllabs.com:443 "GET /api/v3/analyze?host=techjam.wwpass.com&publish=off&ignoreMismatch=on&all=done&fromCache=on&maxAge=36 HTTP/1.1" 403 199
2021-11-15 08:32:34 root	ERROR	Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/lib/wwpass/python3/bin/ssllabs/__init__.py", line 203, in _poll_api
    return self._handle_api_error(requests.get(_url)).json()
  File "/usr/lib/wwpass/python3/bin/ssllabs/__init__.py", line 112, in _handle_api_error
    for error in response.json().get('errors') or ()) \
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Note that request returned HTTP code `403`, but `_die_on_error()` is not called because attempt to parse JSON (which is definitely empty in this case) fails with exception.

Two. `analyze()` expects `_poll_api()` to return dictionary, but it returns `False` on unexpected exceptions, which causes further exception:
```python3
2021-11-15 08:32:34 SSLLabsAccess	ERROR	Assessment error: 'bool' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib/wwpass/python3/bin/SSLLabsAccess.py", line 71, in getData
    ret = assessment.analyze(
  File "/usr/lib/wwpass/python3/bin/ssllabs/__init__.py", line 327, in analyze
    LOGGER.debug('Testing {} host(s)'.format(len(_status.get('endpoints'))))
AttributeError: 'bool' object has no attribute 'get'
```
The provided fix prevents `False` from `_poll_api()` reaching return value analysis.

Also, couple of lines that do nothing are removed.

### CODE REVIEW

**Comment by jolaf** [comment]
Updated with some improved fixes.

**Comment by takeshixx** [comment]
Thanks for the contribution! I will have to test these changes first before I will merge them. I hope to get it done in the next couple of days.

**Comment by jolaf** [comment]
Cool, thanks!!

**Comment by jolaf** [comment]
Any chance for moving forward with this?

**Comment by takeshixx** [comment]
Sorry for the long wait. I was confused by the amohnt of commits but I finally found some time to test it and it looks good. Thanks for the contribution!

**Comment by jolaf** [comment]
Thanks!!

**Pull request merged**
