### PR TITLE
Cached data returned faster; debug logging improved

### PR DESCRIPTION
**Pull request by jolaf**
It turned out that in some cases the lib does more API requests than needed.

Moreover, it seems that with recent updates to the SSL Labs servers in some cases that leads to malfunction when the lib does an extra request after the full results have already been returned, and that causes a new assessment to start.

This pull request adjusts the code so that each API call is checked and if the full results are available they are returned right away with no further requests which improves reliability and makes cached information returned faster.

In particular:
_trigger_new_assessment() and _poll_api() refactored to allow return of a complete cached result at once if it happens

Also logging (particularly debug logging) is adjusted - it helped to uncover the problems mentioned above.

In particular:
 _handle_api_error() now returns JSON and prints it for debugging purposes

### CODE REVIEW

**Comment by jolaf** [comment]
Please feel free to ask if any issues or questions arise.
Thanks!

**Comment by takeshixx** [comment]
Thanks for the PR, sorry for the delay. There is a problem with 859609723723834c53ae460122760cf2f8e4ef9f: `_handle_api_error()` should not return json as this breaks functionality. E.g. `_check_api_info()` relies on the response object:

```python
    try:
        response = self._handle_api_error(requests.get('{}info'.format(self.API_URL)))
    except requests.ConnectionError:
        self._die_on_error('[ERROR] Provided API URL is unavailable.')
...
self.CLIENT_MAX_ASSESSMENTS = response.get('clientMaxAssessments')
self.CURRENT_ASSESSMENTS = response.get('currentAssessments')
self.MAX_ASSESSMENTS = response.get('maxAssessments')
```

`_handle_api_error()` is meant to *only* check whether an error happened during the request. If there is no error, it should return the response object as is. I think it should stay like the future.

**Comment by jolaf** [comment]
Sorry, but I can't see how this breaks anything, as soon as _all_ calls to `_handle_api_error()` in original code that do something with the result, look like `_handle_api_error(...).json()`, `_check_api_info()` included. I see no exceptions. Do I miss anything?

**Comment by takeshixx** [comment]
Sorry, there was a misunderstanding from my side. You are right, it does not break the functionality. However I would prefer to keep returning the complete response object in `_handle_api_error()` instead of only the JSON body. The other changes look good, looking forward to merge the PR.

**Comment by jolaf** [comment]
Ok, I see your point. Reverted that change.
Thanks!

**Comment by takeshixx** [comment]
I merged it, thanks again for the contribution! :ok_hand:

**Pull request merged**
